### ISSUE TITLE
Missing API Key

### ISSUE THREAD

**Issue by OmegaWulf** [fileformat/bitrise-step-appcenter-app-release#13]
I've set everything up using the Bitrise Workflow editor and have the api key inserted as a secret. 

I'm getting the error "Missing required input: appcenter_api_token" even when using  "TestApiToken."

<img width="762" alt="Screen Shot 2019-10-21 at 3 45 49 PM" src="https://user-images.githubusercontent.com/42750678/67248723-3c545e80-f41a-11e9-9b2d-a32301f6ef20.png">

**Comment by karolpiateknet** [comment]
How have you solved that @OmegaWulf ?
