### ISSUE TITLE
Could not upload a new release version

### ISSUE THREAD

**Issue by dungnart** [fileformat/bitrise-step-appcenter-app-release#4]
I always get this message error.

`API call failed with 404: {"message":"Not found. Context ID: 4ae382a9-4b00-44b5-9242-d232a7253a06","statusCode":404,"code":"Not Found"}`

 Am I wrong any configuration? Please let me know. Thank you!

**Comment by TobiasSuhrborg** [comment]
I am having the same issue =(
Any updates on this?

**Comment by dungnart** [comment]
It seems work for now. Can you check again, @TobiasSuhrborg ?

**Comment by fileformat** [comment]
This generally means one of the parameters doesn't match a settings at AppCenter.  Please include the previous couple of log lines: that should show exactly which URL is failing & which value needs to be fixed.
