### ISSUE TITLE
Expose an output variable with download URL.

### ISSUE THREAD

**Issue by MiSikora** [fileformat/bitrise-step-appcenter-app-release#9]
It would be nice to expose a download URL after the upload so it can be processed by other steps like Slack or JIRA comments.

**Comment by mcaldas** [comment]
Any chance this can be implementes?

**Comment by NLS-kbaer** [comment]
We really need this too.

**Comment by Xerosigma** [comment]
We've got two requests pending that should help solve this:
https://github.com/fileformat/bitrise-step-appcenter-app-release/pull/19
https://github.com/fileformat/bitrise-step-appcenter-app-release/pull/20

**Comment by bettola** [comment]
Any update on this one?

**Comment by MiSikora** [comment]
Closing as there is an official step.

https://github.com/bitrise-steplib/steps-appcenter-deploy-android
